# Generated by Django 5.2 on 2025-07-30 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('markers', models.JSONField(help_text='Array of marker coordinates [lat, lng]')),
                ('route_type', models.CharField(choices=[('round_trip', 'Round Trip'), ('one_way', 'One Way')], default='round_trip', max_length=50)),
                ('transportation', models.CharField(choices=[('driving-car', 'Driving'), ('cycling-regular', 'Cycling'), ('foot-walking', 'Walking')], default='driving-car', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_routes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
